### ISSUE TITLE
error in Makefile

### ISSUE THREAD

**Issue by vchong** [KYVENetwork/chain#121]
https://github.com/KYVENetwork/chain/blob/v1.3.0/Makefile#L2 gives below error:
```
$ go version | cut -c 14- | cut -d' ' -f1 | cut -d'.' -f1 -f2
cut: only one type of list may be specified
Try 'cut --help' for more information.
```

This works:
```
$ go version | cut -c 14- | cut -d' ' -f1 | cut -d'.' -f1,2
1.20
```

Please fix asap. Thanks!

**Comment by vchong** [comment]
#122

**Comment by mbreithecker** [comment]
Hey,
thank you for submitting this issue and the fix. 
Tested it on both, linux and macos and both work now 👍
