### ISSUE TITLE
Problem with denom

### ISSUE THREAD

**Issue by MantiCoreGit** [KYVENetwork/chain#17]
In some cases when installing kyve for mainnet we can receive incorrect denom error (`100000` instead of expected `ukyve`)
How to reproduce:
Installation to clear server with `make install`, Go 1.19.4
Solution:
In Makefile replace
```DENOM ?= ukyve```
with
```DENOM := ukyve```

**Comment by johnletey** [comment]
Hey @MantiCoreGit - first off, thanks for submitting an issue!

Noted, we are happy to replace all conditional assignments with simple assignments in our makefile.
However, I don't think this would resolve the issue.

Could you maybe provide a little more context where this error occurs?
So that we can see if we can reproduce it on our side 😄

**Comment by MantiCoreGit** [comment]
> Hey @MantiCoreGit - first off, thanks for submitting an issue!
> 
> Noted, we are happy to replace all conditional assignments with simple assignments in our makefile. However, I don't think this would resolve the issue.
> 
> Could you maybe provide a little more context where this error occurs? So that we can see if we can reproduce it on our side 😄

Yes, of course, I used Hetzner's AX101 dedicated server (AMD Ryzen™ 9 5950X, 128 GB memory with NVME). Go already has been installed, because I needed it early for few other Cosmos SDK based nodes. Go version 1.19.4, Make version 4.3.
I've created new user and execute as user follow commands:
```
git clone https://github.com/KYVENetwork/chain.git
cd chain
git checkout v1.0.0
make install
```
I checked version of binary. It was follow:
```
# version: v1.0.0
# commit: 82007dd0225a3a0b7c1dfdbb12b1f8bc9a6f9273
```
Then I've run `kyved info` and seen that denom was `1000000`
I tried to add additional argsto command `make install EBV=mainnet` and `make install ENV=default`, but result was same
After that I've checked Makefile, edited it as described in the first message and received right denom

**Comment by johnletey** [comment]
Interesting - so the only way this could happen is if you have the `DENOM` environment variable set.

To definitely prevent this, we will implement your proposed changes 😄

**Comment by MantiCoreGit** [comment]
> Interesting - so the only way this could happen is if you have the `DENOM` environment variable set.
> 
> To definitely prevent this, we will implement your proposed changes 😄

Yes, you're right. Now I remembered. That's the case. I used this variable to set amount of ukyve in 1 kyve for further using for telegram alarm script😄
